[versions]
minecraft = "1.20.4"
parchment-minecraft = "1.20.4"
parchment-mappings = "2024.02.25"

architectury = "11.1.17"

fabric-loader = "0.15.10"
fabric-api = "0.97.0+1.20.4"

fabric-forgeConfigPort = "20.4.3"
fabric-tooltipfix = "1.1.1-1.20"

forge-platform = "1.20.4-49.0.41"

neoforge-platform = "20.4.227"
neoforge-loader = "2"

[plugins]
loom = { id = "dev.architectury.loom", version = "1.6-SNAPSHOT" }
architectury = { id = "architectury-plugin", version = "3.4.155" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
architectury-api = { group = "dev.architectury", name = "architectury", version.ref = "architectury" }

# Fabric specific libraries
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-architectury = { group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury" }

fabric-forgeConfigPort = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "fabric-forgeConfigPort" }
fabric-energy = { group = "teamreborn", name = "energy", version = "3.0.0" }

fabric-tooltipFix = { group = "maven.modrinth", name = "tooltipfix", version.ref = "fabric-tooltipfix" }
fabric-roughlyEnoughItems = { group = "me.shedaniel", name = "RoughlyEnoughItems-fabric", version = "14.0.692" }

forge-platform = { group = "net.minecraftforge", name = "forge", version.ref = "forge-platform" }
forge-architectury = { group = "dev.architectury", name = "architectury-forge", version.ref = "architectury" }

neoforge-platform = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-platform" }
neoforge-architectury = { group = "dev.architectury", name = "architectury-neoforge", version.ref = "architectury" }
